version: '3.8'

services:
  contentmaster:
    build:
      context: .
      dockerfile: Dockerfile
    image: contentmaster:latest
    container_name: contentmaster
    restart: unless-stopped
    ports:
      - "8700:8700"
    volumes:
      - contentmaster_data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - TZ=UTC
      - APPLICATION_ROOT=/contentmaster


volumes:
  contentmaster_data:
    name: contentmaster_data